on: [push, pull_request]

name: Continuous integration

jobs:
  cross-compile:
    name: Cross compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7-unknown-linux-gnueabihf
          - powerpc-unknown-linux-gnu
          - powerpc64-unknown-linux-gnu
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      # Note that this does not test the `protobuf` feature (for now). See reasoning in https://github.com/prometheus/client_rust/pull/98/.
      - run: cargo check --target=${{ matrix.target }}
